// GENERATED by scripts/import-youtube.mjs — do not edit by hand.
export const CLIMBING_TERM_DICT: Record<string, { zh: string; example: string }> = {
  "boulder": {
    "zh": "抱石线路",
    "example": "This boulder is low percentage."
  },
  "lead": {
    "zh": "难度/先锋攀",
    "example": "The lead final starts at eight."
  },
  "speed": {
    "zh": "速度赛",
    "example": "She races speed tomorrow."
  },
  "flash": {
    "zh": "一把完攀(无预习)",
    "example": "A flash changes the scoreboard."
  },
  "top": {
    "zh": "完攀点/顶点",
    "example": "She is close to the top."
  },
  "topped": {
    "zh": "完攀了",
    "example": "She topped this boulder."
  },
  "zone": {
    "zh": "Zone 得分点",
    "example": "The zone can still matter."
  },
  "attempt": {
    "zh": "尝试/次数",
    "example": "She has time for another attempt."
  },
  "appeal": {
    "zh": "申诉",
    "example": "The team can appeal the decision."
  },
  "confirmed": {
    "zh": "确认有效",
    "example": "The top was confirmed."
  },
  "scoreboard": {
    "zh": "记分牌",
    "example": "Watch the scoreboard on the left."
  },
  "isolation": {
    "zh": "隔离区",
    "example": "Athletes wait in isolation."
  },
  "qualification": {
    "zh": "资格赛",
    "example": "She came through qualification easily."
  },
  "semi-final": {
    "zh": "半决赛",
    "example": "The semi-final round was brutal."
  },
  "final": {
    "zh": "决赛",
    "example": "The final is stacked this year."
  },
  "clock": {
    "zh": "计时钟",
    "example": "The clock is still running."
  },
  "countdown": {
    "zh": "倒计时",
    "example": "Ten seconds on the countdown."
  },
  "route setter": {
    "zh": "定线员",
    "example": "The route setter intended a jump."
  },
  "setting": {
    "zh": "定线",
    "example": "The setting rewards creativity."
  },
  "beta": {
    "zh": "动作解法/攻略",
    "example": "He found smarter beta."
  },
  "hold": {
    "zh": "岩点/手点",
    "example": "That hold is difficult to use."
  },
  "crimp": {
    "zh": "小边/扣点",
    "example": "She holds the crimp carefully."
  },
  "sloper": {
    "zh": "圆支点/斜面点",
    "example": "That sloper is hard to trust."
  },
  "jug": {
    "zh": "大把手点",
    "example": "Rest on the jug before the crux."
  },
  "pinch": {
    "zh": "捏点",
    "example": "The pinch requires thumb strength."
  },
  "pocket": {
    "zh": "指洞点",
    "example": "She two-finger pockets up."
  },
  "undercling": {
    "zh": "反抠点",
    "example": "She moves into the undercling."
  },
  "sidepull": {
    "zh": "侧拉点",
    "example": "The sidepull sets up the cross."
  },
  "gaston": {
    "zh": "反推点",
    "example": "A gaston opens the sequence."
  },
  "volume": {
    "zh": "大体积岩点",
    "example": "The volume changes the body position."
  },
  "arete": {
    "zh": "岩棱",
    "example": "She wraps the arete."
  },
  "slab": {
    "zh": "偏平衡的板壁",
    "example": "The slab rewards balance and patience."
  },
  "overhang": {
    "zh": "仰角/屋檐壁",
    "example": "The overhang is steep."
  },
  "roof": {
    "zh": "大屋檐",
    "example": "The roof section is powerful."
  },
  "crack": {
    "zh": "裂缝",
    "example": "She jams the crack."
  },
  "foothold": {
    "zh": "脚点",
    "example": "The foothold is glassy."
  },
  "chip": {
    "zh": "小碎点",
    "example": "Only a chip for the left foot."
  },
  "move": {
    "zh": "动作",
    "example": "That move requires commitment."
  },
  "sequence": {
    "zh": "动作序列",
    "example": "This final sequence is delicate."
  },
  "dyno": {
    "zh": "动态跳跃",
    "example": "She sticks the dyno."
  },
  "mantle": {
    "zh": "撑起/翻上去",
    "example": "She has to mantle over the volume."
  },
  "match": {
    "zh": "双手并点",
    "example": "She needs to make the match."
  },
  "cross": {
    "zh": "交叉手",
    "example": "The cross-through is the key."
  },
  "flag": {
    "zh": "平衡摆腿",
    "example": "A flag keeps her hips in."
  },
  "drop knee": {
    "zh": "压膝/落膝",
    "example": "The drop knee locks her in."
  },
  "heel hook": {
    "zh": "脚跟钩",
    "example": "The heel hook saves energy."
  },
  "heel": {
    "zh": "脚跟技术/脚跟挂点",
    "example": "She keeps trusting the heel."
  },
  "toe hook": {
    "zh": "脚尖钩",
    "example": "The toe hook holds the swing."
  },
  "bicycle": {
    "zh": "对踩(heel/toe 夹点)",
    "example": "A bicycle clamps the hold."
  },
  "campus": {
    "zh": "不用脚的纯上肢攀爬",
    "example": "He campuses through the roof."
  },
  "smear": {
    "zh": "踩墙/抹点",
    "example": "She smears on the wall."
  },
  "footwork": {
    "zh": "脚法",
    "example": "Her footwork is silent."
  },
  "foot": {
    "zh": "脚点/踩点",
    "example": "The right foot is important here."
  },
  "toe": {
    "zh": "脚尖",
    "example": "She needs to point her toe."
  },
  "kneebar": {
    "zh": "膝杠休息",
    "example": "A kneebar gives a hands-off rest."
  },
  "lock off": {
    "zh": "锁定",
    "example": "She locks off the next move."
  },
  "deadpoint": {
    "zh": "死点发力",
    "example": "A deadpoint to the lip."
  },
  "coordination": {
    "zh": "协调发力",
    "example": "A coordination jump opens the boulder."
  },
  "run and jump": {
    "zh": "助跑跳跃",
    "example": "A run and jump starts the final."
  },
  "paddle": {
    "zh": "划手发力",
    "example": "She paddles through the coordination move."
  },
  "flexibility": {
    "zh": "柔韧性",
    "example": "That move requires flexibility."
  },
  "balance": {
    "zh": "平衡",
    "example": "Balance decides this slab."
  },
  "tension": {
    "zh": "身体张力",
    "example": "Keep the tension through the core."
  },
  "core": {
    "zh": "核心",
    "example": "The core keeps her feet on."
  },
  "shoulder": {
    "zh": "肩部",
    "example": "That move loads the shoulder."
  },
  "pumped": {
    "zh": "前臂酸胀/泵感",
    "example": "Her arms are pumped."
  },
  "reach": {
    "zh": "臂展/伸手够点",
    "example": "She reaches over to the next hold."
  },
  "height": {
    "zh": "身高",
    "example": "Height matters on this move."
  },
  "commit": {
    "zh": "果断投入动作",
    "example": "She has to commit to the move."
  },
  "committed": {
    "zh": "果断投入",
    "example": "She fully committed to the jump."
  },
  "cruising": {
    "zh": "做得很顺",
    "example": "She is cruising through the lower section."
  },
  "tenuous": {
    "zh": "很不稳/很微妙",
    "example": "It is such a tenuous move."
  },
  "delicate": {
    "zh": "细腻/微妙",
    "example": "A delicate foot swap."
  },
  "powerful": {
    "zh": "爆发力强",
    "example": "A powerful jump to the finish."
  },
  "low percentage": {
    "zh": "成功率低",
    "example": "This is a low percentage boulder."
  },
  "high percentage": {
    "zh": "成功率高",
    "example": "The jug is a high percentage move."
  },
  "crux": {
    "zh": "难点/关键段",
    "example": "This is the crux of the boulder."
  },
  "slipped": {
    "zh": "滑掉",
    "example": "She slipped after the match."
  },
  "peeled off": {
    "zh": "从墙上剥落掉落",
    "example": "She peeled off near the top."
  },
  "fall": {
    "zh": "掉落",
    "example": "That was the first fall."
  },
  "stuck": {
    "zh": "粘住/稳稳接住",
    "example": "She stuck the move perfectly."
  },
  "swing": {
    "zh": "摆荡",
    "example": "The swing almost pulled her off."
  },
  "wobble": {
    "zh": "晃动/不稳",
    "example": "There was a bit of a wobble."
  },
  "fight for it": {
    "zh": "费力完成",
    "example": "She had to fight for that move."
  },
  "gutted": {
    "zh": "非常失落",
    "example": "She looked gutted after the fall."
  },
  "stoked": {
    "zh": "超兴奋",
    "example": "She is stoked with the top."
  },
  "comfortable": {
    "zh": "游刃有余",
    "example": "She looks comfortable on the slab."
  },
  "patient": {
    "zh": "耐心",
    "example": "She stays patient on the balance moves."
  }
};
