// GENERATED by scripts/import-youtube.mjs — do not edit by hand.
import type { VideoEntry, VideoSummary } from '../../types';

const loaders: Record<string, () => Promise<{ video: VideoEntry }>> = {
  'a-complete-guide-to-climbing-movement-and-technique-gtiggs-y2ny': () => import('./a-complete-guide-to-climbing-movement-and-technique-gtiggs-y2ny.video'),
  'bern-2025-wb-rescut': () => import('./bern-2025-wb-rescut.video'),
};

export const videoSummaries: VideoSummary[] = [
  {"id":"a-complete-guide-to-climbing-movement-and-technique-gtiggs-y2ny","title":"A COMPLETE Guide to CLIMBING MOVEMENT AND TECHNIQUE","sourceUrl":"https://www.youtube.com/watch?v=gtIGgs_y2nY","sourceLabel":"A COMPLETE Guide to CLIMBING MOVEMENT AND TECHNIQUE | Richardsons Climbing","youtubeId":"gtIGgs_y2nY","channel":"Richardsons Climbing","category":"technique","categoryLabel":"Technique / 攀岩技巧","level":"beginner","mediaUrl":"/media/a-complete-guide-to-climbing-movement-and-technique-gtiggs-y2ny.mp4","mediaStartTime":0,"durationSeconds":743,"captionKind":"auto","importedAt":"2026-08-22","cueCount":99,"studyCueCount":88,"needsTranslationCount":0},
  {"id":"bern-2025-wb-rescut","title":"Women's Boulder Final | Bern 2025 智能重切","sourceUrl":"https://www.youtube.com/watch?v=CPhZ18zmrBs","sourceLabel":"Women's Boulder Final | Bern 2025 智能重切 | World Climbing","youtubeId":"CPhZ18zmrBs","channel":"World Climbing","category":"world-cup","categoryLabel":"World Cup / 世界杯赛事","level":"intermediate","mediaUrl":"/media/bern-2025-wb-10m31-40m32-web.mp4","mediaStartTime":631,"durationSeconds":1801,"captionKind":"auto","importedAt":"2026-07-24","cueCount":670,"studyCueCount":472,"needsTranslationCount":0}
];

export async function loadVideo(id: string): Promise<VideoEntry | undefined> {
  const loader = loaders[id];
  if (!loader) return undefined;
  const loaded = await loader();
  return loaded.video;
}
